// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: test.proto

//go:build protoopaque

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IP struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Address string                 `protobuf:"bytes,1,opt,name=Address,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IP) Reset() {
	*x = IP{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IP) ProtoMessage() {}

func (x *IP) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IP) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *IP) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

type IP_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Address string
}

func (b0 IP_builder) Build() *IP {
	m0 := &IP{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Address = b.Address
	return m0
}

type URL struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Scheme string                 `protobuf:"bytes,1,opt,name=scheme,proto3"`
	xxx_hidden_Url    string                 `protobuf:"bytes,2,opt,name=url,proto3"`
	xxx_hidden_Port   int32                  `protobuf:"varint,3,opt,name=port,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URL) GetScheme() string {
	if x != nil {
		return x.xxx_hidden_Scheme
	}
	return ""
}

func (x *URL) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *URL) GetPort() int32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *URL) SetScheme(v string) {
	x.xxx_hidden_Scheme = v
}

func (x *URL) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

func (x *URL) SetPort(v int32) {
	x.xxx_hidden_Port = v
}

type URL_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// below is an example where the line-specific comment should take precedence
	// over the "doc" comment, which is known to be more free-form. On the
	// resulting struct field, you should see `valid:"http|https"` added, not
	// `valid:"-"`.
	//
	// @gotags: valid:"-"
	Scheme string
	Url    string
	// Test legacy field name.
	// @inject_tags: valid:"nonzero"
	Port int32
}

func (b0 URL_builder) Build() *URL {
	m0 := &URL{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Scheme = b.Scheme
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Port = b.Port
	return m0
}

type Params struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_XXX_Deprecated string                 `protobuf:"bytes,2,opt,name=XXX__deprecated,json=XXXDeprecated,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Params) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Params) GetXXX_Deprecated() string {
	if x != nil {
		return x.xxx_hidden_XXX_Deprecated
	}
	return ""
}

func (x *Params) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Params) SetXXX_Deprecated(v string) {
	x.xxx_hidden_XXX_Deprecated = v
}

type Params_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// @gotags: validate:"omitempty"
	Id string
	// gets converted into XXX_Deprecated, for use with testing pre-v1.4.x protoc-gen-go
	// functionality that exposes unknown fields as public.
	XXX_Deprecated string
}

func (b0 Params_builder) Build() *Params {
	m0 := &Params{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_XXX_Deprecated = b.XXX_Deprecated
	return m0
}

type Record struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_TestAny   *anypb.Any             `protobuf:"bytes,2,opt,name=test_any,json=testAny,proto3"`
	xxx_hidden_TestEmpty *emptypb.Empty         `protobuf:"bytes,3,opt,name=test_empty,json=testEmpty,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Record) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Record) GetTestAny() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_TestAny
	}
	return nil
}

func (x *Record) GetTestEmpty() *emptypb.Empty {
	if x != nil {
		return x.xxx_hidden_TestEmpty
	}
	return nil
}

func (x *Record) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Record) SetTestAny(v *anypb.Any) {
	x.xxx_hidden_TestAny = v
}

func (x *Record) SetTestEmpty(v *emptypb.Empty) {
	x.xxx_hidden_TestEmpty = v
}

func (x *Record) HasTestAny() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TestAny != nil
}

func (x *Record) HasTestEmpty() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TestEmpty != nil
}

func (x *Record) ClearTestAny() {
	x.xxx_hidden_TestAny = nil
}

func (x *Record) ClearTestEmpty() {
	x.xxx_hidden_TestEmpty = nil
}

type Record_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// @gotags: validate:"omitempty"
	Id        string
	TestAny   *anypb.Any
	TestEmpty *emptypb.Empty
}

func (b0 Record_builder) Build() *Record {
	m0 := &Record{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_TestAny = b.TestAny
	x.xxx_hidden_TestEmpty = b.TestEmpty
	return m0
}

type OneOfObject struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FooBar isOneOfObject_FooBar   `protobuf_oneof:"foo_bar"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OneOfObject) Reset() {
	*x = OneOfObject{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfObject) ProtoMessage() {}

func (x *OneOfObject) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OneOfObject) GetFoo() string {
	if x != nil {
		if x, ok := x.xxx_hidden_FooBar.(*oneOfObject_Foo); ok {
			return x.Foo
		}
	}
	return ""
}

func (x *OneOfObject) GetBar() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_FooBar.(*oneOfObject_Bar); ok {
			return x.Bar
		}
	}
	return 0
}

func (x *OneOfObject) SetFoo(v string) {
	x.xxx_hidden_FooBar = &oneOfObject_Foo{v}
}

func (x *OneOfObject) SetBar(v int64) {
	x.xxx_hidden_FooBar = &oneOfObject_Bar{v}
}

func (x *OneOfObject) HasFooBar() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FooBar != nil
}

func (x *OneOfObject) HasFoo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_FooBar.(*oneOfObject_Foo)
	return ok
}

func (x *OneOfObject) HasBar() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_FooBar.(*oneOfObject_Bar)
	return ok
}

func (x *OneOfObject) ClearFooBar() {
	x.xxx_hidden_FooBar = nil
}

func (x *OneOfObject) ClearFoo() {
	if _, ok := x.xxx_hidden_FooBar.(*oneOfObject_Foo); ok {
		x.xxx_hidden_FooBar = nil
	}
}

func (x *OneOfObject) ClearBar() {
	if _, ok := x.xxx_hidden_FooBar.(*oneOfObject_Bar); ok {
		x.xxx_hidden_FooBar = nil
	}
}

const OneOfObject_FooBar_not_set_case case_OneOfObject_FooBar = 0
const OneOfObject_Foo_case case_OneOfObject_FooBar = 1
const OneOfObject_Bar_case case_OneOfObject_FooBar = 2

func (x *OneOfObject) WhichFooBar() case_OneOfObject_FooBar {
	if x == nil {
		return OneOfObject_FooBar_not_set_case
	}
	switch x.xxx_hidden_FooBar.(type) {
	case *oneOfObject_Foo:
		return OneOfObject_Foo_case
	case *oneOfObject_Bar:
		return OneOfObject_Bar_case
	default:
		return OneOfObject_FooBar_not_set_case
	}
}

type OneOfObject_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// @gotags: tag:"foo_bar"

	// Fields of oneof xxx_hidden_FooBar:
	// @gotags: tag:"foo"
	Foo *string
	// @gotags: tag:"bar"
	Bar *int64
	// -- end of xxx_hidden_FooBar
}

func (b0 OneOfObject_builder) Build() *OneOfObject {
	m0 := &OneOfObject{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Foo != nil {
		x.xxx_hidden_FooBar = &oneOfObject_Foo{*b.Foo}
	}
	if b.Bar != nil {
		x.xxx_hidden_FooBar = &oneOfObject_Bar{*b.Bar}
	}
	return m0
}

type case_OneOfObject_FooBar protoreflect.FieldNumber

func (x case_OneOfObject_FooBar) String() string {
	md := file_test_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isOneOfObject_FooBar interface {
	isOneOfObject_FooBar()
}

type oneOfObject_Foo struct {
	// @gotags: tag:"foo"
	Foo string `protobuf:"bytes,1,opt,name=foo,proto3,oneof"`
}

type oneOfObject_Bar struct {
	// @gotags: tag:"bar"
	Bar int64 `protobuf:"varint,2,opt,name=bar,proto3,oneof"`
}

func (*oneOfObject_Foo) isOneOfObject_FooBar() {}

func (*oneOfObject_Bar) isOneOfObject_FooBar() {}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x02pb\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\x02IP\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\"C\n" +
	"\x03URL\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"@\n" +
	"\x06Params\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fXXX__deprecated\x18\x02 \x01(\tR\rXXXDeprecated\"\x80\x01\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\btest_any\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\atestAny\x125\n" +
	"\n" +
	"test_empty\x18\x03 \x01(\v2\x16.google.protobuf.EmptyR\ttestEmpty\"@\n" +
	"\vOneOfObject\x12\x12\n" +
	"\x03foo\x18\x01 \x01(\tH\x00R\x03foo\x12\x12\n" +
	"\x03bar\x18\x02 \x01(\x03H\x00R\x03barB\t\n" +
	"\afoo_bar29\n" +
	"\rStreamService\x12(\n" +
	"\n" +
	"GetRecords\x12\n" +
	".pb.Params\x1a\n" +
	".pb.Record\"\x000\x01B\x05Z\x03/pbb\x06proto3"

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_test_proto_goTypes = []any{
	(*IP)(nil),            // 0: pb.IP
	(*URL)(nil),           // 1: pb.URL
	(*Params)(nil),        // 2: pb.Params
	(*Record)(nil),        // 3: pb.Record
	(*OneOfObject)(nil),   // 4: pb.OneOfObject
	(*anypb.Any)(nil),     // 5: google.protobuf.Any
	(*emptypb.Empty)(nil), // 6: google.protobuf.Empty
}
var file_test_proto_depIdxs = []int32{
	5, // 0: pb.Record.test_any:type_name -> google.protobuf.Any
	6, // 1: pb.Record.test_empty:type_name -> google.protobuf.Empty
	2, // 2: pb.StreamService.GetRecords:input_type -> pb.Params
	3, // 3: pb.StreamService.GetRecords:output_type -> pb.Record
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[4].OneofWrappers = []any{
		(*oneOfObject_Foo)(nil),
		(*oneOfObject_Bar)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
